# use leakyrelu and finetune best pointgroup model(m=32, onecyclelr)
GENERAL:
  task: train  # train, test
  manual_seed: 123
  model_dir: model/seggroup/segspgsemleaky.py
  dataset_dir: data/scannetv2_inst.py

DATA:
  data_root: dataset
  dataset: scannetv2
  train_dir: train_normal_seg
  val_dir: val_normal_seg
  test_dir: val_normal_seg
  filename_suffix: _inst_nostuff.pth

  cache: True

  classes: 20
  ignore_label: -100

  input_channel: 3
  scale: 50   # voxel_size = 1 / scale, scale 50(2cm)
  batch_size: 4
  full_scale: [128, 512]
  max_npoint: 250000
  mode: 4 # 4=mean
  use_overseg: True
  spg_postfix: _inst_nostuff_superpointgraph_dmax5cm_v2_light.json
  sample_seg_size: 128  # num of points to sample on each segment

STRUCTURE:
  model_name: segspgsemleaky
  m: 32 # 16 or 32
  block_residual: True
  block_reps: 2
  segment_fea: pointnet  # maxpool, avgpool, pointnet
  segment_fea_dim: 32   # feature size of segment
  graph_layer: sageconv
  graph_aggregator_type: pool  # mean, gcn, pool, lstm

  use_coords: True
  use_normal: False


TRAIN:
  epochs: 384
  train_workers: 16 # data loader workers
  optim: Adam # Adam or SGD
  lr: 0.001
  step_epoch: 384
  multiplier: 0.5
  momentum: 0.9
  weight_decay: 0.0001
  save_freq: 16  # also eval_freq
  loss_weight: [1.0, 0, 0, 0] # semantic_loss, offset_norm_loss, offset_dir_loss, score_loss
  focal_loss: False
  fg_thresh: 0.75
  bg_thresh: 0.25

  score_scale: 50 # the minimal voxel size is 2cm
  score_fullscale: 14
  score_mode: 4 # mean

  max_num_segs: -1  # -1 means not constrain segment num

  pretrain_path: pretrained_models/pointgroupleaky_run1_scannet-000000512.pth
  pretrain_module: [input_conv, unet, output_layer, linear, offset, offset_linear, score_unet, score_outputlayer, score_linear]
  fix_module: [input_conv, unet, output_layer, linear, offset, offset_linear, score_unet, score_outputlayer, score_linear]
  is_distributed: False

GROUP:
  ### point grouping
  cluster_radius: 0.03
  cluster_meanActive: 50
  cluster_shift_meanActive: 300
  cluster_npoint_thre: 50 # 50

  prepare_epochs: 128

TEST:
  split: val
  test_epoch: 384
  test_workers: 16
  test_seed: 567

  TEST_NMS_THRESH: 0.3
  TEST_SCORE_THRESH: 0.09
  TEST_NPOINT_THRESH: 100

  eval: True
  save_semantic: False
  save_pt_offsets: False
  save_instance: False
  save_spg_edge_pred: False

  test_upper_bound: False
  cluster_implicit_parts: True